name: CI

on: #trigger
  
  workflow_dispatch: #manual button to run this workflow
  push:
    branches:
      - main
    paths:
    #  - 'src/**'
      - 'src/*'

jobs:
  hello: # name of the job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7 #use the latest Github checkout for files in the repo
      
      - name: Show trigger
        run: echo "Triggered by ${{ github.event_name }}"
      
      - name: Show environment
        run: |
          echo "Hello from GitHub Actions" # print something
          uname -a # name of the operating system
          pwd #print the working directory / folder
      - name: List files
        run: ls -la
      
      # Prints the contents of src/index.html to the workflow log
      - name: list contents of index.html
        run: cat src/index.html
